[package]
name = "waitingroom-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
foundations = { workspace = true }
log = "0.4.21"
