---
# Telemetry settings
telemetry:
  # Distributed tracing settings
  tracing:
    # Enables tracing.
    enabled: true
    # The address of the Jaeger Thrift (UDP) agent.
    jaeger_tracing_server_addr: "127.0.0.1:6831"
    # Overrides the bind address for the reporter API.
    # By default, the reporter API is only exposed on the loopback
    # interface. This won't work in environments where the
    # Jaeger agent is on another host (for example, Docker).
    # Must have the same address family as `jaeger_tracing_server_addr`.
    jaeger_reporter_bind_addr: ~
    # Sampling ratio.
    #
    # This can be any fractional value between `0.0` and `1.0`.
    # Where `1.0` means "sample everything", and `0.0` means "don't sample anything".
    sampling_ratio: 1.0
    # Settings for rate limiting emission of traces
    rate_limit:
      # Whether to enable rate limiting of events
      enabled: false
      # Maximum number of events that can be emitted per second
      max_events_per_second: 0
  # Logging settings.
  logging:
    # Specifies log output.
    output: terminal
    # The format to use for log messages.
    format: text
    # Set the logging verbosity level.
    verbosity: INFO
    # A list of field keys to redact when emitting logs.
    #
    # This might be useful to hide certain fields in production logs as they may
    # contain sensitive information, but allow them in testing environment.
    redact_keys: []
    # Settings for rate limiting emission of log events
    rate_limit:
      # Whether to enable rate limiting of events
      enabled: false
      # Maximum number of events that can be emitted per second
      max_events_per_second: 0
    # Configure log volume metrics.
    log_volume_metrics:
      # Whether to enable log volume metrics
      enabled: false
  # Metrics settings.
  metrics:
    # How the metrics service identifier defined in `ServiceInfo` is used
    # for this service.
    service_name_format: metric_prefix
    # Whether to report optional metrics in the telemetry server.
    report_optional: false
  # Memory profiler settings
  memory_profiler:
    # Enables memory profiling
    enabled: false
    # Value between `0` and `64` which specifies the number of bytes of
    # allocation activity between samples as `number_of_bytes = 2 ^ sample_interval`.
    #
    # Increasing the `sample_interval` decreases profile fidelity, but also decreases the
    # computational overhead.
    #
    # The default is `19` (2 ^ 19 = 512KiB).
    sample_interval: 19
    # Enables [seccomp] sandboxing of syscalls made by [jemalloc] during heap profile collection.
    #
    # [seccomp]: https://en.wikipedia.org/wiki/Seccomp
    # [jemalloc]: https://github.com/jemalloc/jemalloc
    sandbox_profiling_syscalls: true
  # Server settings.
  server:
    # Enables telemetry server
    enabled: true
    # Telemetry server address.
    addr: "127.0.0.1:8989"
