[package]
name = "waitingroom-stresser"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
reqwest = { version = "0.12.5", features = ["cookies"] }
reqwest_cookie_store = "0.8.0"
tokio = { version = "1.38.0", features = ["full"] }
